stages:
  - install
  - build
  - deploy

install:
  stage: install
  image: node:18-alpine
  script:
    - npm install

build:
  stage: build
  script:
    - npm run build

deploy:
  stage: deploy
  script:
    - echo "Deploying to Hostinger"
    - scp -P 65002 -r ./ u935944634@145.223.108.64:/home/u935944634/public_html
  only:
    - main
